version: '3'

services:
  
  server: 
    build: ./server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    expose:
     - 3001  
    ports:  
     - 3001:3001
    command: npm start

  client: 
   build: ./client
   environment:
      CHOKIDAR_USEPOLLING: "true"
   expose:
     - 3000  
   ports:  
     - 3000:3000
   links:
     - server
   command: npm start
  